[0.452s] Invoking command in '/ros2_ws/build/f1tenth_mapping': CMAKE_PREFIX_PATH=/opt/ros/foxy /usr/bin/cmake /ros2_ws/src/f1tenth_mapping -DCMAKE_INSTALL_PREFIX=/ros2_ws/install/f1tenth_mapping
[0.658s] -- The C compiler identification is GNU 9.4.0
[0.807s] -- The CXX compiler identification is GNU 9.4.0
[0.818s] -- Check for working C compiler: /usr/bin/cc
[0.920s] -- Check for working C compiler: /usr/bin/cc -- works
[0.921s] -- Detecting C compiler ABI info
[1.023s] -- Detecting C compiler ABI info - done
[1.040s] -- Detecting C compile features
[1.040s] -- Detecting C compile features - done
[1.044s] -- Check for working CXX compiler: /usr/bin/c++
[1.157s] -- Check for working CXX compiler: /usr/bin/c++ -- works
[1.158s] -- Detecting CXX compiler ABI info
[1.272s] -- Detecting CXX compiler ABI info - done
[1.293s] -- Detecting CXX compile features
[1.293s] -- Detecting CXX compile features - done
[1.308s] -- Found ament_cmake: 0.9.12 (/opt/ros/foxy/share/ament_cmake/cmake)
[1.350s] -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
[1.350s] -- Using PYTHON_EXECUTABLE: /usr/bin/python3
[1.632s] Invoked command in '/ros2_ws/build/f1tenth_mapping' returned '-2': CMAKE_PREFIX_PATH=/opt/ros/foxy /usr/bin/cmake /ros2_ws/src/f1tenth_mapping -DCMAKE_INSTALL_PREFIX=/ros2_ws/install/f1tenth_mapping
[1.636s] Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 67, in execute
    loop.run_until_complete(future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/build.py", line 59, in build
    rc = await extension.build(
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 87, in build
    rc = await self._reconfigure(args, env)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 182, in _reconfigure
    buildfile = get_buildfile(cmake_cache)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/__init__.py", line 112, in get_buildfile
    if 'Ninja' in generator:
TypeError: argument of type 'NoneType' is not iterable
